# Generated by Django 3.2.4 on 2021-06-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0003_auto_20210614_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
