# Generated by Django 3.2.4 on 2021-06-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0009_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameLCourse', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('1', 'DH-CD'), ('2', 'Bo tro'), ('3', 'luyen thi DH'), ('4', 'Boi duong HSG'), ('6', 'Lop6-9'), ('7', 'Luyen thi vao 6'), ('8', 'Lop1-5'), ('9', 'Hoc nghe')], max_length=200, null=True)),
                ('discount', models.CharField(max_length=200, null=True)),
                ('courseImg', models.ImageField(blank=True, max_length=254, null=True, upload_to='courseFile')),
            ],
        ),
    ]
