# Generated by Django 3.2.4 on 2021-07-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0013_comment_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video',
        ),
    ]
