# Generated by Django 3.2.4 on 2021-07-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0014_auto_20210703_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraccounts.courses'),
        ),
    ]
