# Generated by Django 3.2.4 on 2021-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0021_auto_20210704_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namecategory', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
