# Generated by Django 3.2.4 on 2021-07-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0029_auto_20210712_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('paragraph1', models.TextField(max_length=100)),
                ('paragraph2', models.TextField(max_length=100)),
                ('paragraph3', models.TextField(max_length=100)),
                ('img1', models.ImageField(blank=True, default='', max_length=254, null=True, upload_to='blogfile')),
                ('img2', models.ImageField(blank=True, default='', max_length=254, null=True, upload_to='blogfile')),
                ('img3', models.ImageField(blank=True, default='', max_length=254, null=True, upload_to='blogfile')),
                ('author', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
